name: brightness_pro
description: "This package allows you to adjust the screen brightness using drag and slider functionalities."
version: 0.0.3
homepage: https://github.com/SwanFlutter/brightnessPro.

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  screen_brightness: ^0.2.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:


